package puzzles

import "testing"

func TestCountTimelines(t *testing.T) {
	test := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	beamStart, splitters, height := parseDiagram(test)

	if got, want := countTimelines(beamStart, splitters, height), 40; got != want {
		t.Errorf("Expected %d got %d", want, got)
	}
}

func TestParseDiagram(t *testing.T) {
	test := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	beamStart, splitters, height := parseDiagram(test)

	if beamStart.x != 7 || beamStart.y != 0 {
		t.Errorf("Expected %v got %v", beam{7, 0}, beamStart)
	}

	// 7 rows
	if len(splitters) != 22 {
		t.Errorf("Expected %d got %d", 22, len(splitters))
	}

	if height !=  16 {
		t.Errorf("Expected %d got %d", 16, height)
	}
}
